server:
  port: 9991

# Database Configuration (PostgreSQL)
#spring:
#  application:
#    name: stock-management
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/stock-management
#    username: postgres
#    password: smey44
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#  sql:
#    init:
#      mode: always

# MYSQL
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    name: mysql
    url: jdbc:mysql://localhost:3306/stock-management
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
  sql:
    init:
      mode: always


# SWAGGER
springdoc:
  api-docs:
    enabled: true
  show-actuator: true
