-- Insert roles
INSERT INTO ROLES (ID, NAME, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (gen_random_uuid(), 'ADMIN', NOW(), 'system', NOW(), 'system');

INSERT INTO ROLES (ID, NAME, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (gen_random_uuid(), 'USER', NOW(), 'system', NOW(), 'system');

-- Insert permissions
INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (gen_random_uuid(), 'admin:create', NOW(), 'system', NOW(), 'system');

INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (gen_random_uuid(), 'admin:get', NOW(), 'system', NOW(), 'system');

INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (gen_random_uuid(), 'admin:update', NOW(), 'system', NOW(), 'system');

INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (gen_random_uuid(), 'admin:delete', NOW(), 'system', NOW(), 'system');

INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (gen_random_uuid(), 'user:get', NOW(), 'system', NOW(), 'system');

-- Insert role-permission relations
INSERT INTO ROLE_PERMISSION_RELATION_TABLE (ROLE_ID, PERMISSION_ID)
SELECT r.ID, p.ID FROM ROLES r, PERMISSIONS p
WHERE r.NAME = 'ADMIN' AND p.NAME = 'admin:create';

INSERT INTO ROLE_PERMISSION_RELATION_TABLE (ROLE_ID, PERMISSION_ID)
SELECT r.ID, p.ID FROM ROLES r, PERMISSIONS p
WHERE r.NAME = 'ADMIN' AND p.NAME = 'admin:get';

INSERT INTO ROLE_PERMISSION_RELATION_TABLE (ROLE_ID, PERMISSION_ID)
SELECT r.ID, p.ID FROM ROLES r, PERMISSIONS p
WHERE r.NAME = 'ADMIN' AND p.NAME = 'admin:update';

INSERT INTO ROLE_PERMISSION_RELATION_TABLE (ROLE_ID, PERMISSION_ID)
SELECT r.ID, p.ID FROM ROLES r, PERMISSIONS p
WHERE r.NAME = 'ADMIN' AND p.NAME = 'admin:delete';

INSERT INTO ROLE_PERMISSION_RELATION_TABLE (ROLE_ID, PERMISSION_ID)
SELECT r.ID, p.ID FROM ROLES r, PERMISSIONS p
WHERE r.NAME = 'USER' AND p.NAME = 'user:get';

